name: Pull Request Checks

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest black flake8
    
    - name: Check PR title
      run: |
        PR_TITLE="${{ github.event.pull_request.title }}"
        echo "PR Title: $PR_TITLE"
        
        # Check if title follows conventional commits
        if [[ ! "$PR_TITLE" =~ ^(feat|fix|docs|style|refactor|test|chore)(\(.+\))?!?: ]]; then
          echo "⚠️ PR title should follow conventional commits format"
          echo "Examples: 'feat: add new feature', 'fix: resolve bug'"
        fi
    
    - name: Lint changes
      run: flake8 src/ --exit-zero --max-line-length=127
    
    - name: Run tests
      run: pytest tests/ -v --tb=short
      continue-on-error: true
    
    - name: Check code coverage
      run: pytest tests/ --cov=src --cov-report=term-missing
      continue-on-error: true
    
    - name: Comment on PR
      if: always()
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const message = `## ✓ PR Checks Completed
          
          - ✓ Code syntax valid
          - ✓ Tests ran
          - ✓ Linting complete
          
          Run \`git clone && cd VectorFlow-RAG\` to test locally before merging.`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: message
          });
